name: Deploy to Firebase Hosting (web)
on:
  push:
    branches: [ main ]   # change if your default branch is different
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build the PWA that lives in /web
      - name: Build web
        working-directory: web
        run: |
          npm ci
          npm run build

      # Deploy Hosting using the official action
      - name: Deploy to Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: YOUR_PROJECT_ID_HERE   # e.g., taskbox-matt
          channelId: live                   # deploy straight to your live site
          entryPoint: .                     # firebase.json is at repo root
